# agents:
#     queue: '${DEPLOY_AGENTS_QUEUE}'
env:
#  ENVIRONMENT: "dev"
  DEPLOY_AGENTS_QUEUE: "grow-tina-qa-provisioner"

steps:
  - label: "Pension E2E Test"
    agents:
      queue: "${DEPLOY_AGENTS_QUEUE}"
    command: "buildkite-signed-pipeline upload .buildkite/pension-test.yml"
