env:
  COMPOSE_FILE: "./buildkite.docker-compose.yml"
  DEPLOY_AGENTS_QUEUE: "grow-tina-dev-quality"
      

steps:
  - label: ":test_tube: Playwright test"
    branches: 'main'
    command: 'buildkite-signed-pipeline upload .buildkite/e2e-test.yml'  
